server:
  port: 8081
eureka:
  client:
    service-url:
      #配置eureka服务的地址
      defaultZone: http://127.0.0.1/eureka
    #false不需要将自己注册在注册中心，如果是集群部署eureka那就设置为true
    register-with-eureka: false
    #是否需要搜索服务信息
    fetch-registry: false
