server:
  port: 8888
spring:
  application:
    name: mall-order
eureka:
  client:
    ## 是否需要搜索服务信息
    fetch-registry: true
    service-url:
      ## 注册中心服务地址
      defaultZone: http://127.0.0.1:8081/eureka
    ## 是否需要将自己注册到注册中心
    register-with-eureka: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表显示的参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

